#!/usr/bin/env python3
"""Generate a minimal valid .docx test file for SlimLO conversion testing.

A .docx file is an OOXML ZIP archive containing:
  [Content_Types].xml — content type declarations
  _rels/.rels         — root relationships
  word/document.xml   — main document content
  word/_rels/document.xml.rels — document relationships

This script creates a simple document with:
  - A title paragraph (bold, large)
  - A normal text paragraph
  - A bullet list
  - A paragraph with italic text
"""

import os
import zipfile

CONTENT_TYPES = """\
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml"
    ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>"""

RELS = """\
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
    Target="word/document.xml"/>
</Relationships>"""

DOC_RELS = """\
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
</Relationships>"""

DOCUMENT = """\
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
            xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <w:body>
    <!-- Title -->
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="48"/>
        </w:rPr>
        <w:t>SlimLO Test Document</w:t>
      </w:r>
    </w:p>

    <!-- Normal paragraph -->
    <w:p>
      <w:r>
        <w:t>This is a test document for verifying OOXML to PDF conversion via SlimLO.</w:t>
      </w:r>
    </w:p>

    <!-- Paragraph with mixed formatting -->
    <w:p>
      <w:r>
        <w:t xml:space="preserve">It contains </w:t>
      </w:r>
      <w:r>
        <w:rPr><w:b/></w:rPr>
        <w:t>bold</w:t>
      </w:r>
      <w:r>
        <w:t xml:space="preserve">, </w:t>
      </w:r>
      <w:r>
        <w:rPr><w:i/></w:rPr>
        <w:t>italic</w:t>
      </w:r>
      <w:r>
        <w:t xml:space="preserve">, and </w:t>
      </w:r>
      <w:r>
        <w:rPr><w:u w:val="single"/></w:rPr>
        <w:t>underlined</w:t>
      </w:r>
      <w:r>
        <w:t xml:space="preserve"> text for formatting verification.</w:t>
      </w:r>
    </w:p>

    <!-- Bullet list (using simple numbering) -->
    <w:p>
      <w:r>
        <w:t>Features tested:</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:ind w:left="720"/>
      </w:pPr>
      <w:r>
        <w:t xml:space="preserve">&#x2022; Text rendering and font handling</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:ind w:left="720"/>
      </w:pPr>
      <w:r>
        <w:t xml:space="preserve">&#x2022; Basic paragraph formatting</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:ind w:left="720"/>
      </w:pPr>
      <w:r>
        <w:t xml:space="preserve">&#x2022; Character styles (bold, italic, underline)</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:ind w:left="720"/>
      </w:pPr>
      <w:r>
        <w:t xml:space="preserve">&#x2022; PDF export via LibreOfficeKit</w:t>
      </w:r>
    </w:p>

    <!-- Footer -->
    <w:p>
      <w:pPr>
        <w:jc w:val="right"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:color w:val="808080"/>
          <w:sz w:val="20"/>
        </w:rPr>
        <w:t>Generated by SlimLO test suite</w:t>
      </w:r>
    </w:p>

    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"
               w:header="720" w:footer="720" w:gutter="0"/>
    </w:sectPr>
  </w:body>
</w:document>"""


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, "test.docx")

    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", CONTENT_TYPES)
        zf.writestr("_rels/.rels", RELS)
        zf.writestr("word/_rels/document.xml.rels", DOC_RELS)
        zf.writestr("word/document.xml", DOCUMENT)

    print(f"Created {output_path} ({os.path.getsize(output_path)} bytes)")


if __name__ == "__main__":
    main()
